name: Compute & Build p1 (manual)

on:
  workflow_dispatch: {}   # فقط اجرای دستی

permissions:
  contents: write         # اجازهٔ commit/push

jobs:
  compute_and_render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # مرحله محاسبه طبق قواعد ۱–۵ (خروجی: docs/rates.json به‌روز می‌شود)
      - name: Compute p1 deltas and update rates.json
        run: node scripts/compute-p1.mjs

      - name: Commit updated rates.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/rates.json
          git commit -m "compute: update rates.json (p1)" || echo "no changes"

      # پیش‌نیازهای node-canvas برای خروجی PNG
      - name: Install system deps for canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install node deps
        run: npm i canvas@2

      # ساخت تصویر p1.png از روی rates.json
      - name: Render p1.png
        run: node scripts/render-p1.mjs

      - name: Commit p1.png
        run: |
          git add docs/p1.png docs/p1.html
          git commit -m "build: p1.png" || echo "no changes"
          git push
