name: "F1 Rate"

on:
  workflow_dispatch: {}
  # برای زمان‌بندی خودکار، این را باز کن (ساعت استانبول: +03:00)
  # schedule:
  #   - cron: "*/30 * * * *"  # هر 30 دقیقه

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Istanbul
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run scraper
        run: node scripts/f1-rate.mjs

      - name: Show result
        run: |
          echo "Result file:"
          cat data/f1-rate.json || true

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # فقط فایل خروجی را بررسی و در صورت تغییر، کامیت کن
          if [[ -n "$(git status --porcelain data/f1-rate.json)" ]]; then
            git add data/f1-rate.json
            git commit -m "chore: update F1 floor rates (Mashhad) [USD/EUR]"
            git push
          else
            echo "No changes to commit."
          fi
