name: "F1 Rate: test"

on:
  workflow_dispatch: {}   # فقط دستی، طبق خواسته‌ت

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Istanbul
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: "Use Node.js 20"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Prepare data dir + placeholder"
        run: |
          set -e
          mkdir -p rate/data
          TS=$(date -u +%FT%TZ)
          cat > rate/data/f1-exit.json <<EOF
          { "status":"placeholder", "found": false, "message":"no script output yet", "scraped_at":"$TS", "source":"https://t.me/s/dollar_sulaymaniyah", "needle":"کف مشهد" }
          EOF

      - name: "Debug tree (pre-run)"
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f | sort || true

      - name: "Run f1 scraper (best-effort)"
        run: |
          set -x
          if [ -f rate/scripts/f1-rate.mjs ]; then
            node rate/scripts/f1-rate.mjs || true
          elif [ -f scripts/f1-rate.mjs ]; then
            node scripts/f1-rate.mjs || true
          else
            echo "WARN: f1-rate.mjs not found under rate/scripts or scripts; keeping placeholder"
          fi

      - name: "Show result"
        run: |
          echo "Result file:"
          if [ -f rate/data/f1-exit.json ]; then
            cat rate/data/f1-exit.json
          else
            echo "FATAL: rate/data/f1-exit.json still missing"
            exit 1
          fi

      - name: "Commit & push if changed"
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # اگر چیزی تغییر کرده، فقط همین فایل را کامیت کن
          if [[ -n "$(git status --porcelain)" ]]; then
            git add rate/data/f1-exit.json
            git commit -m "chore(f1): update Sulaymaniyah کف مشهد"
            git push
          else
            echo "No changes to commit."
          fi
