name: "f1-real"

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "*/10 * * * *"   # اختیاری: هر ۱۰ دقیقه

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Istanbul

      # قفل نرم ±٪ نسبت به مرجع (پیش‌فرض ۲۰٪)
      REALRATE_GUARD_PCT: "20"
      # مرجع دستی (اختیاری). خالی بگذار تا از روزانه/سالانه یا baseline گرفته شود
      REALRATE_REF: ""

      # پنجره‌ی زمانی معتبر بودن پست‌ها (دقیقه)
      REALRATE_TTL_MIN: "60"
      # حداقل نمونه برای برآورد
      REALRATE_MIN_N: "5"
      # نسبت تریم از دو سر برای میانه‌ی تریم‌شده
      REALRATE_TRIM_FRAC: "0.2"
      # بیشینه‌ی پراکندگی مجاز (٪) — توجه: کلید درست مطابق کد جدید
      REALRATE_SPREAD_PCT: "1.0"
      # Timeout شبکه
      REALRATE_TIMEOUT_MS: "20000"

      DEBUG: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run f1-real
        run: node scripts/f1-real.mjs

      - name: Show result
        run: |
          echo "Result file: data/f1-real.json"
          cat data/f1-real.json || true

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          if [[ -n "$(git status --porcelain data/f1-real.json)" ]]; then
            git add data/f1-real.json
            git commit -m "chore(f1-real): update crowd sell-rate estimate"
            git push
          else
            echo "No changes to commit."
          fi
