name: F1 Rate: Sulaymaniyah (کف مشهد)

on:
  workflow_dispatch: {}
  # توجه: عمداً هیچ trigger دیگری فعال نیست. (push/pull_request/schedule حذف)

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Istanbul
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run f1 scraper
        run: node rate/scripts/f1-rate.mjs

      - name: Show result
        run: |
          echo "Result file:"
          cat rate/data/f1-exit.json || true

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add rate/data/f1-exit.json
            git commit -m "chore(f1): update Sulaymaniyah کف مشهد"
            git push
          else
            echo "No changes to commit."
          fi
