name: Fetch Sources (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch_only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch sources (Telegram & Bonbast)
        run: node scripts/sources.mjs

      - name: Commit sources.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/sources.json || true
          git commit -m "fetch: update data/sources.json" || echo "no changes"

      - name: Upload sources artifact
        uses: actions/upload-artifact@v4
        with:
          name: fetched-sources
          path: data/sources.json
          if-no-files-found: ignore
          retention-days: 3
